#!/bin/bash

pname=$(pwd)
cd "C:/Users/chris/.my_shell_scripts/helper_scripts"
source utils.sh

yninput "Do you want to ${BYellow}add custom folderstructure?${Color_Off} (${Cyan}Y/n${Color_Off}): " addfolderstructure

if [ $addfolderstructure = true ]; then
  yninput " - Do you want to ${BYellow}add the atomic component design?${Color_Off} (${Cyan}Y/n${Color_Off}): " addatomiccomponentdesign
fi

yninput "Do you want to ${BYellow}add custom eslint rules?${Color_Off} (${Cyan}Y/n${Color_Off}): " addeslint
yninput "Do you want to ${BYellow}add custom prettier rules?${Color_Off} (${Cyan}Y/n${Color_Off}): " addprettier
yninput "Do you want to ${BYellow}add testing?${Color_Off} (${Cyan}Y/n${Color_Off}): " addtesting
yninput "Do you want to ${BYellow}add absolut paths?${Color_Off} (${Cyan}Y/n${Color_Off}): " addabsolutpaths

cd $pname

custom_folders=("constants" "helpers" "hooks" "styles" "utils")
comp_folders=("atoms" "molecules" "organisms" "templates" "pages")

if [ $addfolderstructure = true ]; then
  fodlerstructureancor="$pname"
  if [ -d "$pname/src" ]; then
    fodlerstructureancor="$pname/src"
    echo "Adding folders & .gitkeep files to the projects src folder ${fodlerstructureancor}..."
    for folder in "${custom_folders[@]}"; do
      mkdir -p "$fodlerstructureancor/$folder"
      touch "$fodlerstructureancor/$folder/.gitignore"
    done
  else
    echo "Adding folders & .gitkeep files to the projects root folder ${fodlerstructureancor}..."
    for folder in "${custom_folders[@]}"; do
      mkdir -p "$fodlerstructureancor/$folder"
      touch "$fodlerstructureancor/$folder/.gitignore"
    done
  fi
  if [ $addatomiccomponentdesign = true ]; then
    echo "Adding folders & .gitkeep files to the projects components folder ${fodlerstructureancor}/components..."
    for folder in "${comp_folders[@]}"; do
      mkdir -p "$fodlerstructureancor/components/$folder"
      touch "$fodlerstructureancor/components/$folder/.gitignore"
    done
  fi
fi
