#!/usr/bin/env bash

# Renders a text based list of options that can be selected by the
# user using up, down and enter keys and returns the chosen option.
#
#   Arguments   : list of options, maximum of 256
#                 "opt1" "opt2" ...
#   Return value: selected index (0 for opt1, 1 for opt2 ...)

PATH=$PATH:$(dirname $0)/helper_scripts

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/setup_scripts"

clear

plain_options=($(find_executable_files_in_dir $DIR))
echo ${plain_options[@]}
draw_options=($(generate_colored_text "${plain_options[@]}"))

echo "Select what kind of project you want to initialize using up/down keys and enter to confirm:"
echo

draw_arrow_select_menu "${draw_options[@]}"
choice1=$?
clear

$DIR/${plain_options[$choice1]}
