#!/bin/bash

if [ -z "$1" ]; then
  echo "No parameters provided."
else
  cd $1
fi

files=()
while IFS= read -r -d '' file; do
  if [[ -x "$file" ]]; then
    # remove the leading "./" from the filename
    file="${file#.\/}"
    file="${file// /:}"
    files+=("$file")
  fi
done < <(find . -maxdepth 1 -type f -print0)

printf "%s\n" "${files[@]}" | sort
