#!/bin/bash

if [ -z "$*" ]; then
  echo "No parameters provided."
else
  color_reset=$(tput sgr0)

  files=("$@")
  colored_files=()

  colors=($(tput colors))
  i=1
  for file in "${files[@]}"; do
    file="${file// /_}"
    color=$(tput setaf "$i")
    plain_file="${file//_/ }"
    colored_files+=("${color}${file}${color_reset}")
    ((i++))
  done

  printf '%s\n' "${colored_files[@]}"
fi
