#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

projecttype=$(basename $0)

read -p "Enter your desired projectname (leave empty for the default): " projectname
if [ -z "$projectname" ]; then
    projectname="my-app"
fi

echo "Select the type of your "${projecttype#./}" project $projectname with up/down keys and enter to confirm:"
echo

cd "$DIR"

type_options=("typescript" "javascript")

source draw_arrow_select_menu "${type_options[@]}"
choice=$SELECTED
