#!/usr/bin/env bash

# Renders a text based list of options that can be selected by the
# user using up, down and enter keys and returns the chosen option.
#
#   Arguments   : list of options, maximum of 256
#                 "opt1" "opt2" ...
#   Return value: selected index (0 for opt1, 1 for opt2 ...)
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

projecttype=$(basename $0)

read -p "Enter your desired projectname (leave empty for the default): " projectname
if [ -z "$projectname" ]; then
    projectname="my-app"
fi

echo "Select the type of your "${projecttype#./}" project $projectname with up/down keys and enter to confirm:"
echo

cd "$DIR"

options=("typescript" "javascript")

source draw_arrow_select_menu "${options[@]}"
choice=$SELECTED
